#!/usr/bin/env bash

echo "==> Updating software sources..."
sudo apt-get update

echo "==> Installing available packaged software..."
sudo apt-get install libjson0 libjson0-dev libjson-c2 libjson-c-dev libjson0 libjson0-dev libssl1.0.0 tree

echo "==> Building Mosquitto"
wget http://mosquitto.org/files/source/mosquitto-1.4.2.tar.gz
tar zxvf mosquitto-1.4.2.tar.gz
cd mosquitto-1.4.2/
sudo apt-get install build-essential python quilt devscripts python-setuptools python3
sudo apt-get install libc-ares-dev
sudo apt-get install uuid-dev
make WITH_LIBWEBSOCKETS=yes
sudo make install
sudo rm mosquitto-1.4.2.tar.gz

echo "==> Installing Slacker client"
sudo pip install slacker-cli

echo "==> Downloading GitHub Release Download Tool..."
wget -q https://gist.githubusercontent.com/Illizian/9e4854f93498db1a9058d06e87eeafed/raw/b583311a9df332e1d77c4866ad1cb523959050c2/gh-dl-release
mv gh-dl-release ${HOME}/bin
chmod +x ${HOME}/bin/gh-dl-release

echo "==> Downloading OPKG Utils @ 0.3.2 ..."
wget -q http://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils/snapshot/opkg-utils-0.3.2.tar.gz
sudo tar -xvf opkg-utils-0.3.2.tar.gz -C ${HOME}/bin --strip-components=1

echo "==> Downloading Latest Buildroot..."
gh-dl-release AST-UK/integra-buildroot latest buildroot.tgz

echo "==> Installating Latest Buildroot..."
sudo tar -C / -xzf buildroot.tgz
sudo rm buildroot.tgz
